### PR TITLE
Add Incubator example with external NuRV monitor server.

### PR DESCRIPTION
**Pull request by Valdemartt**
This example contains code for running a simulated scenario of the Incubator example, where the lid is lifted which leads to the detection of an anomaly. The Incubator is equipped with energy saving capabilities that should be turned on when such an anomaly is detected. The external monitor server tool called NuRV is used to verify this by sending traces of the system state to the monitoring server. 
README still needs to be updated, but is expected to be so when the other Incubator example is finished to ensure consistency.

### CODE REVIEW

**Comment by prasadtalasila** [comment]
@Valdemartt, Please consider the following suggestions:

1. Remove the unused files, ex:tests, past experimental data and any other unused python modules.
2. Update the README with steps to run your example. Detailed explanation can wait till other incubator examples are done.
3. Add the URL of incubator github repo, and commit hash of the code taken from the incubator git repo. It will be handy later on.

Thanks

**Comment by Valdemartt** [comment]
@prasadtalasila, most (if not all) unused files have now been removed and I have updated the readme and added reference to Incubator repos with specific commit hash.

**Comment by prasadtalasila** [comment]
@Valdemartt 
Please see the logs:

<details>

<summary>The AMQP exchanges on the RabbitMQ server:</summary>

|        name         |  type   |
|:---|:---|
|                     | direct  |
| amq.direct          | direct  |
| amq.fanout          | fanout  |
| amq.headers         | headers |
| amq.match           | headers |
| amq.rabbitmq.trace  | topic   |
| amq.topic           | topic   |
| fmi_digital_twin    | direct  |
| fmi_digital_twin_sh | direct  |
|                     | direct  |
| amq.direct          | direct  |
| amq.fanout          | fanout  |
| amq.headers         | headers |
| amq.match           | headers |
| amq.rabbitmq.trace  | topic   |
| amq.topic           | topic   |
|                     | direct  |
||
| Incubator_AMQP      | topic   |
| amq.direct          | direct  |
| amq.fanout          | fanout  |
| amq.headers         | headers |
| amq.match           | headers |
| amq.rabbitmq.trace  | topic   |
| amq.topic           | topic   |
| fmi_digital_twin    | direct  |
| fmi_digital_twin_sh | direct  |
|                     | direct  |
| amq.direct          | direct  |
| amq.fanout          | fanout  |
| amq.headers         | headers |
| amq.match           | headers |
| amq.rabbitmq.trace  | topic   |
| amq.topic           | topic   |
|                     | direct  |
||
| Incubator_AMQP      | topic   |
| amq.direct          | direct  |
| amq.fanout          | fanout  |
| amq.headers         | headers |
| amq.match           | headers |
| amq.rabbitmq.trace  | topic   |
| amq.topic           | topic   |
| fmi_digital_twin    | direct  |
| fmi_digital_twin_sh | direct  |
|                     | direct  |
||
| Incubator_AMQP      | topic   |
| amq.direct          | direct  |
| amq.fanout          | fanout  |
| amq.headers         | headers |
| amq.match           | headers |
| amq.rabbitmq.trace  | topic   |
| amq.topic           | topic   |
| fmi_digital_twin    | direct  |
| fmi_digital_twin_sh | direct  |
|                     | direct  |
| amq.direct          | direct  |
| amq.fanout          | fanout  |
| amq.headers         | headers |
| amq.match           | headers |
| amq.rabbitmq.trace  | topic   |
| amq.topic           | topic   |
|                     | direct  |
| Incubator_AMQP      | topic   |
| amq.direct          | direct  |
| amq.fanout          | fanout  |
| amq.headers         | headers |
| amq.match           | headers |
| amq.rabbitmq.trace  | topic   |
| amq.topic           | topic   |
| fmi_digital_twin    | direct  |
| fmi_digital_twin_sh | direct  |
|                     | direct  |
| amq.direct          | direct  |
| amq.fanout          | fanout  |
| amq.headers         | headers |
| amq.match           | headers |
| amq.rabbitmq.trace  | topic   |
| amq.topic           | topic   |
|                     | direct  |
| |
| Incubator_AMQP      | topic   |
| amq.direct          | direct  |
| amq.fanout          | fanout  |
| amq.headers         | headers |
| amq.match           | headers |
| amq.rabbitmq.trace  | topic   |
| amq.topic           | topic   |
| fmi_digital_twin    | direct  |
| fmi_digital_twin_sh | direct  |

</details>

**NOTE**: Not sure why but multiple exchanges of the same name exist. Is it possible to check for existence of an exchange before creating one? Also the execution log (the images below) shows the RabbitMQ connection being closed immediately. Is it anyway related to multiple exchanges?

## The execution log:

image
...................
image

**Comment by prasadtalasila** [comment]
> @prasadtalasila, most (if not all) unused files have now been removed and I have updated the readme and added reference to Incubator repos with specific commit hash.

thanks

**Comment by prasadtalasila** [comment]
Some questions:

There is some data stored in `data` directory. Is it used in anyway? If it is, please place the same in `/workspace/examples/data/<twin_name>/output` directory.

### Reuse

Potential changes to promote reuse of the same incubator code across all the examples:

1. Does the example work with relative pathnames? @mortenhaahr wants to use relative paths and they might actually allow reuse of the same incubator code in multiple examples.
2. Structuring of the code:

    ```bash
    /workspace/examples/common/digital_twins/incubator
                |
                | reuse
                \/
    /workspace/examples/common/digital_twins/
          incubator_NuRV
              conf file
              lifecycle scripts (wrappers to lifecycle scripts of incubator and NuRV specific commands)
          incubator_NuRV_service
              conf file
              lifecycle scripts (wrappers to lifecycle scripts of incubator and NuRV specific commands)
          incubator_TeSSLa
              conf file
              lifecycle scripts (wrappers to lifecycle scripts of incubator and TeSSLA specific commands)
    ```

These are only suggestions and I am hoping that duplicate work goes down significantly across all the examples. Suggestions from both of you - @Valdemartt and @mortenhaahr are welcome. Thanks again for the PR.

**Comment by prasadtalasila** [comment]
Can you please upload the InfluxDB dashboard config to the example code? It becomes easier to see the visualisations.

**Comment by Valdemartt** [comment]
Regarding multiple RabbitMQ AMQP exchanges:
I'm using the RabbitMQ class defined in the Incubator example, which uses a third party library (Pika) to declare exchanges. According to the method used (exchange_declare), the exchange is only created if it does not already exist. So I'm puzzled why there are multiple exchanges of the same name and type. Are they all related to my account or do they perhaps span multiple accounts if this is possible?

Regarding the connection closed in logs: 
This is related to how the scenario is run. I'm using separate scripts (implemented by Morten) to send control messages to the incubator. These scripts use a separate connection which is closed when the command has been sent. Perhaps this could be related to the multiple exchanges but I would expect the exchange to be found despite it being a different connection. I could potentially adapt the code to use the same connection.

Regarding the data directory:
This is for storing temporary log files associated with the naming service. The data is not important in terms of the example.

Regarding reuse:
I think we could easily reuse the incubator code and relative path names. I was thinking perhaps (removed the /common/ part for the specific monitors): 
```
/workspace/examples/common/digital_twins/incubator
            |
            | reuse in
            \/
/workspace/examples/digital_twins/
      incubator_NuRV
          conf file
          lifecycle scripts (wrappers to lifecycle scripts of incubator and NuRV specific commands)
      incubator_NuRV_service
          conf file
          lifecycle scripts (wrappers to lifecycle scripts of incubator and NuRV specific commands)
      incubator_TeSSLa
          conf file
          lifecycle scripts (wrappers to lifecycle scripts of incubator and TeSSLA specific commands)
```
What do you think @mortenhaahr ?

Regarding InfluxDB:
I have currently not setup InfluxDB or a dashboard for that matter. What specifically in this example were you thinking here would be beneficial to visualize?

**Comment by mortenhaahr** [comment]
**Regarding the RabbitMQ exchange issue:**
I have the same understanding as Valdemar regarding the exchange_declare function.
I am unable to replicate the issue with the Dockerized version of  RabbitMQ. Perhaps this is because it reboots the containers.

I don't think we can debug it without more information @prasadtalasila.
Who are the Virtual Hosts in the table you provided?
If you could grant us access to the RabbitMQ Management site then we can perhaps be more helpful

**Connection closed in logs**
This also happens with the original Incubator. It happens when we change an actuator on the Incubator, e.g., the heater or the fan and it seems to be intended. It happens inside the `HeaterMock` class:

````python
class HeaterMock(LedMock):
    def __init__(self, rabbitmq_config):
        super(HeaterMock, self).__init__()
        self.rabbitmq_config = rabbitmq_config

        self.state_on = False

    def off(self):
        super(HeaterMock, self).off()
        # Open a new connections everytime because this method is not called very often.
        with Rabbitmq(**self.rabbitmq_config) as con:
            con.send_message(MOCK_HEATER_ON, {"heater": False})

    def on(self):
        super(HeaterMock, self).on()
        # Open a new connections everytime because this method is not called very often.
        with Rabbitmq(**self.rabbitmq_config) as con:
            con.send_message(MOCK_HEATER_ON, {"heater": True})
````
Notice how it opens a RabbitMQ connection whenever on/off is called.

I think the solution is to lower the log level of the RabbitMQ class, as these logs IMO belong to debug.
I've done so on my PR and in commit 6767bc51eec7155c48714f134ba509e8c18db3ed .
(I have also attached the patch - I don't think I have push permission on Valdemar's repo)

[loglevel.txt](https://github.com/INTO-CPS-Association/DTaaS-examples/files/14598201/loglevel.txt)

**Comment by mortenhaahr** [comment]
**Regarding common directory:**
I think this would work and that it is a good idea.
Although we have some slight conflicts between the branches that would need to be settled, I think we should aim for this.

**Regarding InfluxDB**
The dashboard is found in incubator/digital_twin/data_access/influxdbserver/dashboards/incubator_data.json

**Comment by prasadtalasila** [comment]
@mortenhaahr and @Valdemartt thanks for the helpful information. You can replicate the RabbitMQ exchange problem by keeping your RabbitMQ docker container running between multiple iterations (bringing up and taking down) of the incubator docker compose. Perhaps we can wait a bit to debug the RabbitMQ exchange problem.

Let us target to finish the rest of the open threads in this conversation. Thanks.

**Comment by Valdemartt** [comment]
I have now updated my example to use the relative path to the /common/digital_twins/incubator directory. Since you have already made the changes to the Incubator logging configuration, perhaps you can add the common version of your Incubator DT @mortenhaahr which we can both use?

I'm still unsure as to what is expected of the InfluxDB setup in my example. Is it just the visualization of the data trace of the incubator, or should the monitor verdict also be pushed and visualized?

**Comment by prasadtalasila** [comment]
Please use the relative paths w.r.t the working directory of DT lifecycle scripts. The common o5g PR has a shell variable called `O5G_INSTALL_PATH`. This variable is part of DT config. It would be elegant solution for relative paths.

You can place the Onflux dashbard config (json file) in the `digital_twins/<twin name>`. The README can provide instructions to inform the user about uploading the json to Influx application.

Hope the explanation helps.


________________________________

**Comment by mortenhaahr** [comment]
> I have now updated my example to use the relative path to the /common/digital_twins/incubator directory. Since you have already made the changes to the Incubator logging configuration, perhaps you can add the common version of your Incubator DT @mortenhaahr which we can both use?

Working on this. You will have to rebase to merge into my PR then. Not sure if we can keep this PR or have to make a new one

**Comment by mortenhaahr** [comment]
The common folder has now been implemented on #28.
It uses the env variable INCUBATOR_PATH that defaults to `../../../common/digital_twins/incubator`

@Valdemartt please let me know if this causes any issues - and feel free to take inspiration from the lifecycle scripts on my branch.

**Comment by mortenhaahr** [comment]
@Valdemartt  @prasadtalasila  what happened to this branch? It seems that the NuRV example is gone

Edit: Not gone but two mixed with another example

**Pull request closed without merging**
