### PR TITLE
Incubator integration

### PR DESCRIPTION
**Pull request by mortenhaahr**
- Rewrote Incubator example to work without Docker
- Made it follow DTaaS conventions
- Wrote README (based on existing documentation).

### CODE REVIEW

**Comment by prasadtalasila** [comment]
@mortenhaahr Thanks for the PR. It works as expected.

Please see the suggested changes:

1. Remove the unused files, ex: godot files, tests, past experimental data and any other unused python modules.
2. Update the README with explanation of the results seen in Influx dashboards. If there is a way to upload the Influx dashboard config (like done in firefighter example), that would be great. Add a couple of useful screenshots from InfluxDB dashboards.
3. Add the URL of incubator github repo, and **commit hash** of the code taken from the incubator git repo. It will be handy later on.

Thanks.

**Comment by prasadtalasila** [comment]
@mortenhaahr is this a work-in-progress or are you waiting for my review?

**Comment by mortenhaahr** [comment]
> @mortenhaahr is this a work-in-progress or are you waiting for my review?

This is still a work-in-progress.

**Comment by mortenhaahr** [comment]
> Please see the suggested changes:
> 
>     1. Remove the unused files, ex: godot files, tests, past experimental data and any other unused python modules.
> 
>     2. Update the README with explanation of the results seen in Influx dashboards. If there is a way to upload the Influx dashboard config (like done in firefighter example), that would be great. Add a couple of useful screenshots from InfluxDB dashboards.
> 
>     3. Add the URL of incubator github repo, and **commit hash** of the code taken from the incubator git repo. It will be handy later on.

@prasadtalasila Done with 1 and 3.
I propose we create an issue for 2 and handle it after tutorial submission. 

That way I can merge this PR and start integrating the other Incubator examples.

**Pull request merged**
