### PR TITLE
Update NuRV property monitor and reset behavior

### PR DESCRIPTION
**Pull request by Valdemartt**

### CODE REVIEW

**Comment by mortenhaahr** [comment]
Made some minor changes. If @Valdemartt and @prasadtalasila approve then we can merge.

**Comment by Valdemartt** [comment]
> Made some minor changes. If @Valdemartt and @prasadtalasila approve then we can merge.

Looks good to me :)

**Comment by prasadtalasila** [comment]
@mortenhaahr has the PR been checked in the DTaaS workspace? Thanks for clarification.

**Comment by mortenhaahr** [comment]
@prasadtalasila Yes it has. Sorry for not making that clear.

**Comment by prasadtalasila** [comment]
@Valdemartt and @mortenhaahr thanks for the updates

**Pull request merged**
