### PR TITLE
Fix of CORBA ORB not working

### PR DESCRIPTION
**Pull request by mortenhaahr**
The NuRV Monitor Service example stopped working.
@Valdemartt found some bug fixes that are introduced in this PR.

All credits to @Valdemartt

### CODE REVIEW

**Comment by prasadtalasila** [comment]
@mortenhaahr The [lifecycle/create script](https://github.com/INTO-CPS-Association/DTaaS-examples/blob/nurv-monitor-service-fix/digital_twins/incubator-NuRV-monitor-service/lifecycle/create) for this DT is not installing as many packages as that of [plain incubator script](https://github.com/INTO-CPS-Association/DTaaS-examples/blob/main/digital_twins/incubator/lifecycle/create). Is there a tacit assumption of using plain Incubator DT before using the DT with NuRV monitor service?
Thanks for the clarification.

**Comment by prasadtalasila** [comment]
@Valdemartt and @mortenhaahr There seems to be a subtle error when executing this DT. There was an error when it was run the first time but works when it was run again.

```bash
▶ lifecycle/execute
Using LIFECYCLE_PATH: /workspace/examples/digital_twins/incubator-NuRV-monitor-service/lifecycle
Using NURV_PATH: /workspace/examples/digital_twins/incubator-NuRV-monitor-service/lifecycle/../../../common/services/NuRV
Using INCUBATOR_PATH: /workspace/examples/digital_twins/incubator-NuRV-monitor-service/lifecycle/../../../common/digital_twins/incubator
Started omniNames server
Started NuRV server
Established connection with NuRV
Starting incubator
Connected to rabbitmq server.
Running scenario with initial state: lid closed and energy saver on
Setting energy saver mode: enable
Setting G_box to: 0.5763498
State: !anomaly & !energy_saving, verdict: Unknown
State: !anomaly & !energy_saving, verdict: Unknown
State: !anomaly & !energy_saving, verdict: Unknown
State: !anomaly & !energy_saving, verdict: Unknown
State: !anomaly & !energy_saving, verdict: Unknown
State: !anomaly & !energy_saving, verdict: Unknown
State: !anomaly & !energy_saving, verdict: Unknown
State: !anomaly & !energy_saving, verdict: Unknown
```

**Comment by mortenhaahr** [comment]
> @mortenhaahr The [lifecycle/create script](https://github.com/INTO-CPS-Association/DTaaS-examples/blob/nurv-monitor-service-fix/digital_twins/incubator-NuRV-monitor-service/lifecycle/create) for this DT is not installing as many packages as that of [plain incubator script](https://github.com/INTO-CPS-Association/DTaaS-examples/blob/main/digital_twins/incubator/lifecycle/create). Is there a tacit assumption of using plain Incubator DT before using the DT with NuRV monitor service? Thanks for the clarification.

No. This is a bug. I fixed it in the latest commit.

**Comment by mortenhaahr** [comment]
> @Valdemartt and @mortenhaahr There seems to be a subtle error when executing this DT. There was an error when it was run the first time but works when it was run again.

We are aware that there are some instability issues in this example.
But once it gets started then it is stable.

Do you still have the error logs of it??

**Comment by prasadtalasila** [comment]
> > @Valdemartt and @mortenhaahr There seems to be a subtle error when executing this DT. There was an error when it was run the first time but works when it was run again.
> 
> We are aware that there are some instability issues in this example. But once it gets started then it is stable.
> 
> Do you still have the error logs of it??

They look like this:

```bash
▶ lifecycle/execute    
Using LIFECYCLE_PATH: /workspace/examples/digital_twins/incubator-NuRV-monitor-service/lifecycle
Using NURV_PATH: /workspace/examples/digital_twins/incubator-NuRV-monitor-service/lifecycle/../../../common/services/NuRV
Using INCUBATOR_PATH: /workspace/examples/digital_twins/incubator-NuRV-monitor-service/lifecycle/../../../common/digital_twins/incubator
Started omniNames server
Started NuRV server
Established connection with NuRV
Starting incubator
Connected to rabbitmq server.
Running scenario with initial state: lid closed and energy saver on
Setting energy saver mode: enable
Setting G_box to: 0.5763498
An error has occurred
Stopping nurvProcess with pid: 419612
Stopping omniNames with pid: 419608
Stopping incubator with pid: 419621
```

**Comment by prasadtalasila** [comment]
@mortenhaahr I get the following error on a clean workspace.

```log
▶ lifecycle/execute 
Using LIFECYCLE_PATH: /workspace/examples/digital_twins/incubator-NuRV-monitor-service/lifecycle
lifecycle/execute: line 8: .venv/bin/activate: No such file or directory
Using NURV_PATH: /workspace/examples/digital_twins/incubator-NuRV-monitor-service/lifecycle/../../../common/services/NuRV
Using INCUBATOR_PATH: /workspace/examples/digital_twins/incubator-NuRV-monitor-service/lifecycle/../../../common/digital_twins/incubator
Traceback (most recent call last):
  File "execute.py", line 8, in <module>
    from omniORB import CORBA
ModuleNotFoundError: No module named 'omniORB'
(base) 
```

**Comment by mortenhaahr** [comment]
> They look like this:

Had the same error happen to me but it also disappeared when retrying. If it continues I might look into it in a separate fix.


> @mortenhaahr I get the following error on a clean workspace.

I cannot replicate this. I tried to delete my examples folder and rerun the example but it worked as intended.
I also verified that omniorb-py is installed in the create script and everything appears good.
Did the create script successfully execute?

@prasadtalasila can you provide details on this and whether it still happens?

**Comment by prasadtalasila** [comment]
@mortenhaahr The example works for me now. I might have been using the commit before updating the installation script. Thanks for rechecking everything.

**Pull request merged**
