### PR TITLE
Updates README references and acknowledgements

### PR DESCRIPTION
**Pull request by alq-eium**

### CODE REVIEW

**Comment by prasadtalasila** [comment]
@alq-eium , can you please look into the following changes?

1. The script name _main.py_ needs to be changed to _client_xxx.py_
2. The text after the _images/dt-structure.png_ figure needs to be changed to:
    ```md
    The client python script (`client-opcua.py`) does the following actions:
    
    - Reads the variable names and the variable value references from
      the model description file of the Test_DTCONEDAR.FMU.
    - Reads _configuration_freeopcua.ods_ to obtain opcua node IDs and assigns
      those node IDs to the variables read from the FMU
    - Read _configuration_freeopcua.ods_  to fix initial values, parameters and
      some inputs
      (those inputs that are not being measured, a reasonable value is assumed).
    - Read values from PLC using a client OPC.
    - Execute the algorithm with the FMPy library using the .fmu created from
      the compartment model (based on CFD)
    
      - Obtain results.
      - Send by OPC UA protocol the result values to the PLC, to visualize them
        in the SCADA and with the aim to improve the decision-making process of
        the plant operator.
    ```

**Question**: Is there a way to improve dt-structure.png by bringing the information included in [this figure](https://github.com/INTO-CPS-Association/DTaaS-examples/blob/main/digital_twins/opc-ua-waterplant/images/dt-structure.png)?

**Comment by alq-eium** [comment]
@prasadtalasila thank you for the comments, I will update the README with the suggested changes. Regarding the question, it makes sense to combine both schemes into a more comprehensive one. I will draw a new figure.

**Comment by prasadtalasila** [comment]
@alq-eium, can you please make the open changes so that we can merge the PR? Thanks.

**Comment by alq-eium** [comment]
Hi @prasadtalasila I have commited the changes:

- I have added a second page to [images/dt-structure.drawio](https://github.com/alq-eium/DTaaS-examples/blob/electroingenium/digital_twins/opc-ua-electroingenium/images/dt-structure.drawio) where is the new version of the scheme [images/dt-structure2.png](https://github.com/alq-eium/DTaaS-examples/blob/electroingenium/digital_twins/opc-ua-electroingenium/images/dt-structure2.png). I hope you find it OK.
- Some changes to `README.md`

**Comment by alq-eium** [comment]
@prasadtalasila I have changed again the scheme with this one [dt-structure-uv_channel.png](https://github.com/alq-eium/DTaaS-examples/blob/electroingenium/digital_twins/opc-ua-electroingenium/images/dt-structure-uv_channel.png)

**Comment by prasadtalasila** [comment]
@alq-eium thanks for the update. I will check it now.

**Pull request merged**
